import { defineType, defineField } from 'sanity'
import { IceCreamIcon } from '@sanity/icons'

export const recipe = defineType({
  name: 'recipe',
  title: 'Recipe',
  type: 'document',
  icon: IceCreamIcon,
  fields: [
    defineField({
      name: 'title',
      title: 'Recipe Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
      description: 'The name of your recipe (e.g., "Grandma\'s Apple Pie")',
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
      description: 'The URL-friendly version of the title (auto-generated from title)',
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      rows: 3,
      validation: (Rule) => Rule.required(),
      description: 'A brief, appetizing description of the recipe (shown in search results and cards)',
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'reference',
      to: [{ type: 'category' }],
      validation: (Rule) => Rule.required(),
      description: 'The main category this recipe belongs to (e.g., Desserts, Main Dishes)',
    }),
    defineField({
      name: 'subcategory',
      title: 'Subcategory',
      type: 'string',
      description: 'A more specific type (e.g., "Cookies", "Pasta dishes", "Holiday")',
    }),
    defineField({
      name: 'cuisine',
      title: 'Cuisine',
      type: 'string',
      description: 'The style of cooking (e.g., "Italian", "Mexican", "Southern American")',
    }),
    defineField({
      name: 'difficulty',
      title: 'Difficulty',
      type: 'string',
      options: {
        list: [
          { title: 'Easy', value: 'Easy' },
          { title: 'Medium', value: 'Medium' },
          { title: 'Hard', value: 'Hard' },
        ],
        layout: 'radio',
      },
      initialValue: 'Medium',
      description: 'How challenging is this recipe to make?',
    }),
    defineField({
      name: 'servings',
      title: 'Servings',
      type: 'number',
      initialValue: 4,
      description: 'How many people does this recipe serve?',
    }),
    defineField({
      name: 'prepTime',
      title: 'Prep Time',
      type: 'string',
      description: 'Time to prepare ingredients before cooking (e.g., "15 mins", "1 hour")',
    }),
    defineField({
      name: 'cookTime',
      title: 'Cook Time',
      type: 'string',
      description: 'Time spent actively cooking/baking (e.g., "30 mins", "2 hours")',
    }),
    defineField({
      name: 'totalTime',
      title: 'Total Time',
      type: 'string',
      description: 'Total time from start to finish including prep and cook (e.g., "45 mins")',
    }),
    defineField({
      name: 'restTime',
      title: 'Rest/Chill Time',
      type: 'string',
      description: 'Time needed for dough to rise, chilling, or resting (e.g., "30 mins", "Overnight")',
    }),
    defineField({
      name: 'mainImage',
      title: 'Main Image',
      type: 'image',
      options: {
        hotspot: true,
      },
      fields: [
        {
          name: 'alt',
          title: 'Alternative Text',
          type: 'string',
          description: 'Describe the image for screen readers and SEO (e.g., "Slice of apple pie with vanilla ice cream")',
        },
      ],
      validation: (Rule) => Rule.required(),
      description: 'A beautiful photo of the finished dish (required)',
    }),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'reference',
      to: [{ type: 'author' }],
      description: 'Who created or contributed this recipe? (e.g., "Grandma Rose")',
    }),
    defineField({
      name: 'dateCreated',
      title: 'Date Created',
      type: 'datetime',
      initialValue: () => new Date().toISOString(),
      description: 'When this recipe was first added (auto-filled)',
    }),
    defineField({
      name: 'dateModified',
      title: 'Date Modified',
      type: 'datetime',
      initialValue: () => new Date().toISOString(),
      description: 'When this recipe was last updated (auto-filled)',
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        layout: 'tags',
      },
      description: 'Keywords to help people find this recipe (e.g., "holiday", "quick", "vegetarian")',
    }),
    defineField({
      name: 'ingredients',
      title: 'Ingredients',
      type: 'array',
      of: [{ type: 'ingredientGroup' }],
      validation: (Rule) => Rule.required().min(1),
      description: 'List all ingredients needed, organized into groups (e.g., "For the crust", "For the filling")',
    }),
    defineField({
      name: 'instructions',
      title: 'Instructions',
      type: 'array',
      of: [{ type: 'instructionStep' }],
      validation: (Rule) => Rule.required().min(1),
      description: 'Step-by-step directions for making the recipe',
    }),
    defineField({
      name: 'nutrition',
      title: 'Nutrition Information',
      type: 'object',
      fields: [
        { name: 'calories', title: 'Calories', type: 'number', description: 'Calories per serving' },
        { name: 'protein', title: 'Protein', type: 'string', description: 'e.g., "15g"' },
        { name: 'carbs', title: 'Carbohydrates', type: 'string', description: 'e.g., "45g"' },
        { name: 'fat', title: 'Fat', type: 'string', description: 'e.g., "12g"' },
        { name: 'fiber', title: 'Fiber', type: 'string', description: 'e.g., "5g"' },
        { name: 'sugar', title: 'Sugar', type: 'string', description: 'e.g., "20g"' },
        { name: 'sodium', title: 'Sodium', type: 'string', description: 'e.g., "500mg"' },
      ],
      description: 'Optional nutritional information per serving',
    }),
    defineField({
      name: 'notes',
      title: 'Recipe Notes',
      type: 'array',
      of: [{ type: 'text', rows: 2 }],
      description: 'Helpful tips, tricks, or important information about this recipe',
    }),
    defineField({
      name: 'variations',
      title: 'Variations',
      type: 'array',
      of: [{ type: 'text', rows: 2 }],
      description: 'Ways to modify or adapt this recipe (e.g., "Use pecans instead of walnuts")',
    }),
    defineField({
      name: 'storage',
      title: 'Storage Instructions',
      type: 'text',
      rows: 2,
      description: 'How to store leftovers (e.g., "Refrigerate in airtight container for up to 3 days")',
    }),
    defineField({
      name: 'rating',
      title: 'Rating',
      type: 'number',
      validation: (Rule) => Rule.min(0).max(5),
      description: 'Average user rating from 0 to 5 stars',
    }),
    defineField({
      name: 'reviewCount',
      title: 'Review Count',
      type: 'number',
      initialValue: 0,
      description: 'Number of people who have rated this recipe',
    }),
    defineField({
      name: 'featured',
      title: 'Featured Recipe',
      type: 'boolean',
      initialValue: false,
      description: 'Check this to highlight the recipe on the homepage and other featured sections',
    }),
    defineField({
      name: 'isFamilyRecipe',
      title: 'Family Recipe',
      type: 'boolean',
      initialValue: true,
      description: 'Mark as a cherished family recipe (adds special badge)',
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seoFields',
      description: 'Search engine optimization settings (advanced)',
    }),
  ],
  orderings: [
    {
      title: 'Date Created, New',
      name: 'dateCreatedDesc',
      by: [{ field: 'dateCreated', direction: 'desc' }],
    },
    {
      title: 'Title',
      name: 'titleAsc',
      by: [{ field: 'title', direction: 'asc' }],
    },
    {
      title: 'Rating',
      name: 'ratingDesc',
      by: [{ field: 'rating', direction: 'desc' }],
    },
  ],
  preview: {
    select: {
      title: 'title',
      category: 'category.title',
      media: 'mainImage',
      featured: 'featured',
    },
    prepare({ title, category, media, featured }) {
      return {
        title: featured ? `⭐ ${title}` : title,
        subtitle: category || 'Uncategorized',
        media,
      }
    },
  },
})
